import assert from 'node:assert/strict'
import { AdaptiveReadPolicy } from '../extension/read-policy.js'

let now = 1000
const policy = new AdaptiveReadPolicy({ now: () => now, maxDeltaChain: 2, keyframeTtlMs: 1000, focusTtlMs: 500 })
let decision = policy.decide(7)
assert.equal(decision.readMode, 'keyframe')
assert.equal(decision.reason, 'baseline_missing')
policy.complete(7, decision, { snapshotId: 'one' })
decision = policy.decide(7)
assert.equal(decision.readMode, 'delta')
assert.equal(decision.options.since, 'one')
policy.complete(7, decision, { snapshotId: 'two', reset: false })
policy.noteAction(7, 'fill', 'css=#name')
decision = policy.decide(7)
assert.equal(decision.readMode, 'focus')
assert.equal(decision.options.scope, 'css=#name')
assert.equal(decision.options.semanticScope, true)
decision = policy.decide(7)
assert.equal(decision.readMode, 'delta', 'focus is consumed once')
policy.complete(7, decision, { snapshotId: 'three', reset: false })
assert.equal(policy.decide(7).reason, 'delta_chain_limit')
policy.clearTab(7)
decision = policy.decide(7)
policy.complete(7, decision, { snapshotId: 'four' })
now += 1001
assert.equal(policy.decide(7).reason, 'baseline_expired')
policy.noteAction(7, 'click', 'css=#old')
now += 501
assert.notEqual(policy.decide(7).readMode, 'focus', 'stale action focus is ignored')
assert.equal(policy.decide(7, { mode: 'full' }).readMode, 'full')
assert.equal(policy.decide(7, { mode: 'compact', scope: 'css=#x' }).manual, true)
assert.throws(() => policy.decide(7, { mode: 'unknown' }))
const filtered = policy.decide(8, { mode: 'auto', selector: 'button', limit: 10 })
assert.equal(filtered.readMode, 'keyframe')
assert.equal(filtered.options.selector, 'button')
assert.equal(filtered.options.limit, 10)
assert.equal(filtered.options.mode, 'compact')
const directFocus = policy.decide(9, { mode: 'focus', target: 'css=#dialog' })
assert.equal(directFocus.readMode, 'focus')
assert.equal(directFocus.options.scope, 'css=#dialog')
assert.throws(() => policy.decide(9, { mode: 'focus' }), /requires target or scope/)
policy.clearTab(7)
decision = policy.decide(7)
const scene = policy.complete(7, decision, { snapshotId: 'five', reset: true, resetReason: 'change_ratio' })
assert.equal(scene.reason, 'scene_change')
process.stdout.write('adaptive keyframe, delta, focus, expiry and explicit full policy: ok\n')
